# Generated by Django 3.2.18 on 2023-04-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.BooleanField()),
                ('keyword', models.CharField(default=False, max_length=100)),
                ('link', models.CharField(default=False, max_length=100)),
            ],
            options={
                'verbose_name': '작업 정보 테이블',
                'db_table': 'task_data',
            },
        ),
    ]
